# Generated by Django 5.1.4 on 2026-06-06 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academics_subject',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('class_grade', models.CharField(choices=[('10', '10th'), ('11', '11th'), ('12', '12th'), ('dropper', 'Dropper')], max_length=10)),
                ('target_exam', models.CharField(choices=[('jee', 'JEE'), ('neet', 'NEET'), ('boards', 'Boards')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('max_capacity', models.PositiveIntegerField(default=50)),
                ('current_strength', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_teachers', models.ManyToManyField(limit_choices_to={'role': 'teacher'}, related_name='managed_batches', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(related_name='batches', to='academics.subject')),
            ],
            options={
                'db_table': 'academics_batch',
            },
        ),
        migrations.CreateModel(
            name='BatchEnrollment',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.batch')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academics_batchenrollment',
                'indexes': [models.Index(fields=['student', 'status'], name='academics_b_student_0103ea_idx'), models.Index(fields=['batch', 'status'], name='academics_b_batch_i_e4726b_idx')],
                'unique_together': {('student', 'batch')},
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status', 'target_exam'], name='academics_b_status_d58dee_idx'),
        ),
    ]
